services:
  flymetothemoon:
    image: ${DOCKER_REGISTRY-}flymetothemoon
    build:
      context: .
      dockerfile: Fly Me to the Moon/Dockerfile
    depends_on: 
      - db
      
  db:
    image: postgres:16-alpine
    container_name: spaceflight_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Iwan2006
      POSTGRES_DB: Fly_me_to_the_Moon
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Fly_me_to_the_Moon"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
